name = "api-cloudflare"
main = "src/index.ts"
compatibility_date = "2026-04-07"
workers_dev = false

[[routes]]
pattern = "api.thanejoss.com"
custom_domain = true

[[d1_databases]]
binding = "CONTACT_DB"

[vars]
CORS_ALLOW_ORIGIN = "https://thanejoss.com"
