name = "api-cloudflare"
main = "src/index.ts"
compatibility_date = "2026-04-07"
workers_dev = false

[[routes]]
pattern = "api.thanejoss.com"
custom_domain = true

[[d1_databases]]
binding = "CONTACT_DB"
database_name = "api-cloudflare-contact-db"
database_id = "8bb4e04c-9b21-47a4-a531-2077b1049e7b"

[vars]
CORS_ALLOW_ORIGIN = "https://thanejoss.com"
